<?php

if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}


/*
* Register ACF Fields in custom post type Stores
* because wp all import doesn't support wp blocks
*/
if (function_exists('acf_add_local_field_group')) {
	acf_add_local_field_group([
		'key' => 'group_5e762f0517095',
		'title' => '[Canva] - Store Fields',
		'fields' => [
			[
				'key' => 'field_5e762f16d7d88',
				'label' => __('Store name', 'canva-backend'),
				'name' => 'store_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Store Name known to the public or Company Name', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5f9956bb5271b',
				'label' => __('Contact person', 'canva-backend'),
				'name' => 'store_referent',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: John Doe', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e762f46d7d89',
				'label' => __('Address', 'canva-backend'),
				'name' => 'store_address',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			],
			[
				'key' => 'field_5e76300fd7d8d',
				'label' => __('Email 1', 'canva-backend'),
				'name' => 'store_email_1',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: email@store.com', 'canva-backend'),
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'field_5f99566b52719',
				'label' => __('Email 2', 'canva-backend'),
				'name' => 'store_email_2',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: email@store.com', 'canva-backend'),
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'field_5f9959b29e55d',
				'label' => __('Pec email', 'canva-backend'),
				'name' => 'store_pec_email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: email@pec.com', 'canva-backend'),
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'field_5e762f98d7d8c',
				'label' => __('Telephone 1', 'canva-backend'),
				'name' => 'store_phone_1',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: 3356175062', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5f9955ec52717',
				'label' => __('Telephone 2', 'canva-backend'),
				'name' => 'store_phone_2',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: 3356175062', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5f9955f152718',
				'label' => __('Green telephone number', 'canva-backend'),
				'name' => 'store_toll_free_phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '33',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: 8003402456', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e7cadd31d478',
				'label' => 'WhatsApp',
				'name' => 'store_whatsapp',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: 3356175062', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5f9956705271a',
				'label' => 'Telegram',
				'name' => 'store_telegram',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('Example: 3356175062', 'canva-backend'),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e763044d7d8e',
				'label' => __('Website', 'canva-backend'),
				'name' => 'store_website_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => __('https://store.com', 'canva-backend'),
			],
			[
				'key' => 'field_5e763131d7d93',
				'label' => __('Opening hours', 'canva-backend'),
				'name' => 'store_hours',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'layout' => 'block',
				'sub_fields' => [
					[
						'key' => 'field_5f995b232c474',
						'label' => __('Monday', 'canva-backend'),
						'name' => 'monday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995b2f2c475',
						'label' => __('Tuesday', 'canva-backend'),
						'name' => 'tuesday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995b4b2c476',
						'label' => __('Wednesday', 'canva-backend'),
						'name' => 'wednesday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995b7f2c477',
						'label' => __('Thursday', 'canva-backend'),
						'name' => 'thursday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995b912c478',
						'label' => __('Friday', 'canva-backend'),
						'name' => 'friday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995bad2c479',
						'label' => __('Saturday', 'canva-backend'),
						'name' => 'saturday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f995bc12c47a',
						'label' => __('Sunday', 'canva-backend'),
						'name' => 'sunday',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '33',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => __('Example: 09:00 - 13:00 15:00 - 19:00', 'canva-backend'),
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
				],
			],
			[
				'key' => 'field_5f995c582c47b',
				'label' => __('Photo Gallery', 'canva-backend'),
				'name' => 'store_photo_gallery',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'id',
				'preview_size' => '320-free',
				'insert' => 'append',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'field_5e76317fd7d95',
				'label' => __('Description', 'canva-backend'),
				'name' => 'store_description',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			],
			[
				'key' => 'field_5fa7a5ba55ab1',
				'label' => __('Contact form', 'canva-backend'),
				'name' => 'store_cf7_form',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'post_type' => [
					0 => 'wpcf7_contact_form',
				],
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			],
		],
		'location' => [
			[
				[
					'param' => 'post_type',
					'operator' => '==',
					// 'value' => 'stores',
					'value' => apply_filters('canva_acf_store_slug', 'stores'),
				],
			],
		],
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => [
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'slug',
			6 => 'author',
			7 => 'format',
			8 => 'page_attributes',
			9 => 'categories',
			10 => 'tags',
			11 => 'send-trackbacks',
		],
		'active' => true,
		'description' => '',
	]);
}


