<?php

if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}


if (function_exists('acf_add_local_field_group')) {

	acf_add_local_field_group([
		'key' => 'group_5c5070dbe1953',
		'title' => __('People Card', 'canva-backend'),
		'fields' => [
			[
				'key' => 'field_5c507133f4f52',
				'label' => __('First name', 'canva-backend'),
				'name' => 'first_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5c507144f4f53',
				'label' => __('Last name', 'canva-backend'),
				'name' => 'last_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e31b3d12b2bf',
				'label' => __('Nickname', 'canva-backend'),
				'name' => 'nickname',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e31b3d12b2bf23456sd',
				'label' => __('Qualification', 'canva-backend'),
				'name' => 'qualification',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5c507163f4f54',
				'label' => __('Company name', 'canva-backend'),
				'name' => 'company_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5c50719ff4f55',
				'label' => __('Country', 'canva-backend'),
				'name' => 'country',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e31b43a773f3',
				'label' => __('Quote', 'canva-backend'),
				'name' => 'quote',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			],
			[
				'key' => 'field_5c5071b7f4f56',
				'label' => __('Biography', 'canva-backend'),
				'name' => 'biography',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			],
			[
				'key' => 'field_5e31b723fba7c',
				'label' => __('Phone number', 'canva-backend'),
				'name' => 'phone_number',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e31b743fba7d',
				'label' => __('Email', 'canva-backend'),
				'name' => 'email_address',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '50',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'field_5c6d459ce08de',
				'label' => __('Website URL', 'canva-backend'),
				'name' => 'website_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
			],
			[
				'key' => 'field_5c6d45f5e08df',
				'label' => __('Facebook URL', 'canva-backend'),
				'name' => 'facebook_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
			],
			[
				'key' => 'field_5c6d4603e08e0',
				'label' => __('Instagram URL', 'canva-backend'),
				'name' => 'instagram_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
			],
			[
				'key' => 'field_xats22nizl',
				'label' => __('LinkedIn URL', 'canva-backend'),
				'name' => 'linkedin_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '25',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
			],
		],
		'location' => [
			[
				[
					'param' => 'post_type',
					'operator' => '==',
					// 'value' => 'people',
					'value' => apply_filters('canva_cptui_people_slug', 'people'),
				],
			],
		],
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => [
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'slug',
			6 => 'author',
			7 => 'format',
			8 => 'page_attributes',
			9 => 'categories',
			10 => 'send-trackbacks',
		],
		'active' => true,
		'description' => '',
	]);
}
